# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

# this file should be run in the root of the repo
services:
  asr:
    build:
      dockerfile: comps/asr/src/Dockerfile
    image: ${REGISTRY:-opea}/asr:${TAG:-latest}
  asr-openeuler:
    build:
      dockerfile: comps/asr/src/Dockerfile.openEuler
    image: ${REGISTRY:-opea}/asr:${TAG:-latest}-openeuler
