# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

# this file should be run in the root of the repo
services:
  router:
    build:
      dockerfile: comps/router/src/Dockerfile
    image: ${REGISTRY:-opea}/router:${TAG:-latest}
