# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0


include:
  - ../../../third_parties/elasticsearch/deployment/docker_compose/compose.yaml
  - ../../../third_parties/milvus/deployment/docker_compose/compose.yaml
  - ../../../third_parties/neo4j/deployment/docker_compose/compose.yaml
  - ../../../third_parties/opensearch/deployment/docker_compose/compose.yaml
  - ../../../third_parties/pgvector/deployment/docker_compose/compose.yaml
  - ../../../third_parties/qdrant/deployment/docker_compose/compose.yaml
  - ../../../third_parties/redis/deployment/docker_compose/compose.yaml
  - ../../../third_parties/vdms/deployment/docker_compose/compose.yaml
  - ../../../third_parties/tgi/deployment/docker_compose/compose.yaml
  - ../../../third_parties/tei/deployment/docker_compose/compose.yaml

services:

  dataprep-elasticsearch:
    image: ${REGISTRY:-opea}/dataprep:${TAG:-latest}
    container_name: dataprep-elasticsearch
    ports:
      - "${DATAPREP_PORT:-11100}:5000"
    ipc: host
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      DATAPREP_COMPONENT_NAME: "OPEA_DATAPREP_ELASTICSEARCH"
      ES_CONNECTION_STRING: ${ES_CONNECTION_STRING}
      INDEX_NAME: ${INDEX_NAME}
      TEI_EMBEDDING_ENDPOINT: ${TEI_EMBEDDING_ENDPOINT}
      HUGGINGFACEHUB_API_TOKEN: ${HF_TOKEN}
    restart: unless-stopped
    depends_on:
      elasticsearch-vector-db:
        condition: service_healthy

  dataprep-milvus:
    image: ${REGISTRY:-opea}/dataprep:${TAG:-latest}
    container_name: dataprep-milvus-server
    ports:
      - "${DATAPREP_PORT:-11101}:5000"
    ipc: host
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      DATAPREP_COMPONENT_NAME: "OPEA_DATAPREP_MILVUS"
      MILVUS_HOST: ${MILVUS_HOST}
      TEI_EMBEDDING_ENDPOINT: ${TEI_EMBEDDING_ENDPOINT}
      HUGGINGFACEHUB_API_TOKEN: ${HF_TOKEN}
      LOGFLAG: ${LOGFLAG}
    restart: unless-stopped
    depends_on:
      tei-embedding-serving:
        condition: service_healthy
      standalone:
        condition: service_healthy
      etcd:
        condition: service_healthy
      minio:
        condition: service_healthy

  dataprep-neo4j-llamaindex:
    image: ${REGISTRY:-opea}/dataprep:${TAG:-latest}
    container_name: dataprep-neo4j-llamaindex
    depends_on:
      neo4j-apoc:
        condition: service_healthy
      tgi-gaudi-server:
        condition: service_healthy
      tei-embedding-serving:
        condition: service_healthy
    ports:
      - "${DATAPREP_PORT:-11103}:5000"
    ipc: host
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      host_ip: ${host_ip}
      DATAPREP_COMPONENT_NAME: "OPEA_DATAPREP_NEO4J_LLAMAINDEX"
      NEO4J_URL: ${NEO4J_URL}
      NEO4J_USERNAME: ${NEO4J_USERNAME}
      NEO4J_PASSWORD: ${NEO4J_PASSWORD}
      TGI_LLM_ENDPOINT: ${TGI_LLM_ENDPOINT}
      TEI_EMBEDDING_ENDPOINT: ${TEI_EMBEDDING_ENDPOINT}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_EMBEDDING_MODEL: ${OPENAI_EMBEDDING_MODEL}
      OPENAI_LLM_MODEL: ${OPENAI_LLM_MODEL}
      EMBEDDING_MODEL_ID: ${EMBEDDING_MODEL_ID}
      LLM_MODEL_ID: ${LLM_MODEL_ID}
      LOGFLAG: ${LOGFLAG}
      HUGGINGFACEHUB_API_TOKEN: ${HF_TOKEN}
      HF_TOKEN: ${HF_TOKEN}
      MAX_INPUT_TOKENS: ${MAX_INPUT_TOKENS:-4096}
    restart: unless-stopped

  dataprep-opensearch:
    image: ${REGISTRY:-opea}/dataprep:${TAG:-latest}
    container_name: dataprep-opensearch-server
    ports:
      - "${DATAPREP_PORT:-11104}:5000"
    depends_on:
      opensearch-vector-db:
        condition: service_healthy
    ipc: host
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: ${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
      DATAPREP_COMPONENT_NAME: "OPEA_DATAPREP_OPENSEARCH"
      OPENSEARCH_URL: ${OPENSEARCH_URL}
      INDEX_NAME: ${INDEX_NAME}
      HUGGINGFACEHUB_API_TOKEN: ${HF_TOKEN}
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

  dataprep-pgvector:
    image: ${REGISTRY:-opea}/dataprep:${TAG:-latest}
    container_name: dataprep-pgvector-server
    ports:
      - "${DATAPREP_PORT:-11105}:5000"
    depends_on:
      pgvector-db:
        condition: service_healthy
    ipc: host
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      DATAPREP_COMPONENT_NAME: "OPEA_DATAPREP_PGVECTOR"
      PG_CONNECTION_STRING: ${PG_CONNECTION_STRING}
    restart: unless-stopped

  dataprep-pinecone:
    image: ${REGISTRY:-opea}/dataprep:${TAG:-latest}
    container_name: dataprep-pinecone-server
    ports:
      - "${DATAPREP_PORT:-11106}:5000"
    ipc: host
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      DATAPREP_COMPONENT_NAME: "OPEA_DATAPREP_PINECONE"
      PINECONE_API_KEY: ${PINECONE_API_KEY}
      PINECONE_INDEX_NAME: ${PINECONE_INDEX_NAME}
      HUGGINGFACEHUB_API_TOKEN: ${HF_TOKEN}
    restart: unless-stopped

  dataprep-qdrant:
    image: ${REGISTRY:-opea}/dataprep:${TAG:-latest}
    container_name: dataprep-qdrant-server
    depends_on:
      qdrant-vector-db:
        condition: service_healthy
      tei-embedding-serving:
        condition: service_healthy
    ports:
      - "${DATAPREP_PORT:-11107}:5000"
    ipc: host
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      DATAPREP_COMPONENT_NAME: "OPEA_DATAPREP_QDRANT"
      QDRANT_HOST: ${QDRANT_HOST}
      QDRANT_PORT: ${QDRANT_PORT}
      COLLECTION_NAME: ${COLLECTION_NAME}
      TEI_EMBEDDING_ENDPOINT: ${TEI_EMBEDDING_ENDPOINT}
      HUGGINGFACEHUB_API_TOKEN: ${HF_TOKEN}
    restart: unless-stopped

  dataprep-redis:
    image: ${REGISTRY:-opea}/dataprep:${TAG:-latest}
    container_name: dataprep-redis-server
    depends_on:
      redis-vector-db:
        condition: service_healthy
      tei-embedding-serving:
        condition: service_healthy
    ports:
      - "${DATAPREP_PORT:-11108}:5000"
    ipc: host
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      DATAPREP_COMPONENT_NAME: "OPEA_DATAPREP_REDIS"
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_URL: ${REDIS_URL}
      TEI_EMBEDDING_ENDPOINT: ${TEI_EMBEDDING_ENDPOINT}
      INDEX_NAME: ${INDEX_NAME}
      HUGGINGFACEHUB_API_TOKEN: ${HF_TOKEN}
    restart: unless-stopped

  dataprep-multimodal-redis:
    image: ${REGISTRY:-opea}/dataprep:${TAG:-latest}
    container_name: dataprep-multimodal-redis-server
    ports:
      - "${DATAPREP_PORT:-11109}:5000"
    depends_on:
      redis-vector-db:
        condition: service_healthy
    ipc: host
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      MULTIMODAL_DATAPREP: true
      DATAPREP_COMPONENT_NAME: "OPEA_DATAPREP_MULTIMODALREDIS"
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_URL: ${REDIS_URL}
      INDEX_NAME: ${INDEX_NAME}
      LVM_ENDPOINT: ${LVM_ENDPOINT}
      HUGGINGFACEHUB_API_TOKEN: ${HF_TOKEN}
    restart: unless-stopped

  dataprep-vdms:
    image: ${REGISTRY:-opea}/dataprep:${TAG:-latest}
    container_name: dataprep-vdms-server
    ports:
      - "${DATAPREP_PORT:-11110}:5000"
    depends_on:
      vdms-vector-db:
        condition: service_healthy
    ipc: host
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      DATAPREP_COMPONENT_NAME: "OPEA_DATAPREP_VDMS"
      VDMS_HOST: ${VDMS_HOST}
      VDMS_PORT: ${VDMS_PORT}
      COLLECTION_NAME: ${COLLECTION_NAME}
      HUGGINGFACEHUB_API_TOKEN: ${HF_TOKEN}
    restart: unless-stopped

  dataprep-vdms-multimodal:
    image: ${REGISTRY:-opea}/dataprep:${TAG:-latest}
    container_name: dataprep-vdms-multimodal-server
    ports:
      - "${DATAPREP_PORT:-11111}:5000"
    depends_on:
      vdms-vector-db:
        condition: service_healthy
    ipc: host
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      MULTIMODAL_DATAPREP: true
      DATAPREP_COMPONENT_NAME: "OPEA_DATAPREP_MULTIMODALVDMS"
      VDMS_HOST: ${VDMS_HOST}
      VDMS_PORT: ${VDMS_PORT}
      COLLECTION_NAME: ${INDEX_NAME}
    restart: unless-stopped

networks:
  default:
    driver: bridge
  opensearch-net:
