# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

# Default values for lvm-uservice.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

tgi:
  enabled: true
