# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

include:
  - ../../../third_parties/tgi/deployment/docker_compose/compose.yaml

services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5442:5432'
    volumes:
      - ../../src/chinook.sql:/docker-entrypoint-initdb.d/chinook.sql

  text2sql:
    image: opea/text2sql:${TAG:-latest}
    container_name: text2sql-server
    ports:
      - ${TEXT2SQL_PORT:-8080}:8080
    environment:
      - TGI_LLM_ENDPOINT=${TGI_LLM_ENDPOINT}
    depends_on:
      - tgi-server
      - postgres

  text2sql-gaudi:
    image: opea/text2sql:${TAG:-latest}
    container_name: text2sql-gaudi-server
    ports:
      - ${TEXT2SQL_PORT:-8080}:8080
    environment:
      - TGI_LLM_ENDPOINT=${TGI_LLM_ENDPOINT}
    depends_on:
      - tgi-gaudi-server
      - postgres
networks:
  default:
    driver: bridge
