# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

version: "3"
services:
  arangodb:
    image: arangodb/arangodb:latest
    container_name: arangodb
    ports:
      - 8529:8529
    environment:
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      no_proxy: ${no_proxy}
      ARANGO_ROOT_PASSWORD: ${ARANGO_ROOT_PASSWORD}

  feedbackmanagement-arango:
    image: opea/feedbackmanagement-arango:latest
    container_name: feedbackmanagement-arango-server
    ports:
      - "6016:6016"
    ipc: host
    environment:
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      no_proxy: ${no_proxy}
      ARANGO_HOST: ${ARANGO_HOST}
      ARANGO_PORT: ${ARANGO_PORT}
      ARANGO_USERNAME: ${ARANGO_USERNAME}
      ARANGO_PASSWORD: ${ARANGO_PASSWORD}
      DB_NAME: ${DB_NAME}
      COLLECTION_NAME: ${COLLECTION_NAME}
    restart: unless-stopped

networks:
  default:
    driver: bridge
